---
# 하나의 롤은 다음과 같은 디렉터리를 기본 형식으로 가지고 있다.
# 이때 중요한 것은 모든 디렉터리를 다 사용할 필요는 없으며, 필요에 따라 사용하면 된다는 것이다.
# 그리고, 파일을 생성 및 전달하는 목적인 파일과 템플릿을 제외한 모든 항복에는 'main.yml'이라는 파일이 시작점이 된다.

# [defaults]
# 디폴트 변수를 가진다.
# 변수의 우선순위 중에 가장 낮은 변수이다.

# [files]
# 노드에 배포할 파일들이 위치할 디렉터리이다.
# 주로 노드마다 동적으로 변경할 필요가 없는 파일을 전달할 때 사용된다.
# 예를 들면, 웹 페이지 또는 환경 설정 파일 등이 있다.

# [handlers]
# 핸들러를 선언하는 곳

# [meta]
# 의존성이 있는 다른 롤을 선언할 때 사용한다.
# 그렇지만, 이곳은 롤에 대한 추가 정보 작성자의 정보 및 호환 버전 등을 기입하는 목적으로도 사용된다.

# [tasks / 필수항목]
# 플레이북에서 계속 사용되어 왔던 태스크들을 기입하는 곳이다.
# 다른 곳과 다르게 이 항목은 필수적으로 기입되어야 한다.

# [templates]
# 템플릿, 즉 진자2 파일이 위치하는 곳이다.

# [vars 변수]
# 변수들에 대한 정보를 모아두는 곳이다.
# 이때 사용되는 변수는 15번째의 우선순위를 가진다.
- name: Install nginx on the nodes
  hosts: nodes
  become: yes

  roles:
    - { role: ./nginx }